### ISSUE TITLE
Unable to build (cabal could not resolve dependencies)

### ISSUE THREAD

**Issue by gllmhyt** [kmein/gen-dmc#2]
Running Arch Linux, I installed cabal (3.2.0.0) and ghc (8.10.2), cloned gen-dmc and tried to install but I got this error:

```
cabal: Could not resolve dependencies:
[__0] trying: gen-dmc-0.1.0 (user goal)
[__1] next goal: base (dependency of gen-dmc)
[__1] rejecting: base-4.14.1.0/installed-4.14.1.0 (conflict: gen-dmc =>
base^>=4.12.0.0)
[__1] skipping: base-4.14.0.0, base-4.13.0.0 (has the same characteristics
that caused the previous version to fail: excluded by constraint '^>=4.12.0.0'
from 'gen-dmc')
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, gen-dmc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, gen-dmc
```

**Comment by kmein** [comment]
In the most recent commit, I removed all package constraints (that most likely caused your error). It should work now.

**Comment by gllmhyt** [comment]
Thanks for your support. I updated but I'm still getting errors (I'm totally unfamiliar with cabal, I'm not very helpful).

```
~/gen-dmc master* ❯ cabal install  
cabal: Could not resolve dependencies:
[__0] trying: gen-dmc-0.1.0 (user goal)
[__1] trying: diagrams-svg-1.4.3 (dependency of gen-dmc)
[__2] next goal: base (dependency of gen-dmc)
[__2] rejecting: base-4.14.1.0/installed-4.14.1.0 (conflict: diagrams-svg =>
base>=4.7 && <4.14)
[__2] skipping: base-4.14.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.7 && <4.14' from
'diagrams-svg')
[__2] rejecting: base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: base, diagrams-svg, gen-dmc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, diagrams-svg, gen-dmc
```

**Comment by kmein** [comment]
This is what the infamous "cabal hell" looks like (explained [here](https://stackoverflow.com/questions/25869041/whats-the-reason-behind-cabal-dependency-hell)). It basically means that two dependencies of gen-dmc require different versions of the same library, which cabal cannot wrap its head around.

Depending on how important it is to you to get the CLI running, you can install the [Nix](https://nixos.org/) package manager (which works around those packaging conflicts by letting it install two versions of the same package side by side) and running

```shell
nix-build -E '(import <nixpkgs> {}).haskellPackages.callPackage ./. {}'
```

The built binary should then be located in a directory named `result`.

In case you just want to generate an image, you can use the web version hosted here: http://kmein.github.io/gen-dmc.
